### PR TITLE
chore(#20): package is now named inbox451

### PR DESCRIPTION
**Pull request by lmmendes**

### CODE REVIEW

**Comment by lmmendes** [comment]
@Jalmeida1994 I already merged back "Package Vite Frontend Assets using stuffbin #18"

**Review by Jalmeida1994 — APPROVED** [review]
LGTM! I'll add the missing Bruno API requests and probably start a PR to add some small tests. We're getting to a phase where I believe the project is getting more stable. Wha do you think?

**Comment by lmmendes** [comment]
> LGTM! I'll add the missing Bruno API requests and probably start a PR to add some small tests. We're getting to a phase where I believe the project is getting more stable. Wha do you think?

Sounds a great ideia, I'm going to finish this pull-request after lunch, I just noticed that we are missing the "users" endpoint, will be adding it and removing the pull-request from draft.

If you wish to start adding bruno tests, and working at the moment (before I close this pull-request) brach from this pull-request so that you have this latest changes, if needed I will then sync with you before merging.

Now off to the groceries before gf kills me.

**Comment by lmmendes** [comment]
@Jalmeida1994 in a last note, I started moving the services, api handers (controllers) to their own files since I seeing that files were becoming big and confusing, but we can review this, since it doesn't break the internal API since files were created inside the existing package, its just organisation than anything else.

**Comment by lmmendes** [comment]
@Jalmeida1994 we are ready for the review, if you end approving it please merge it else leve comments and I will fix the issue ASAP :D

**Comment by Jalmeida1994** [comment]
@lmmendes Added the route and handler for the single message endpoint. Also added some tests for the bruno requests and the get single message request in bruno too.

**Comment by Jalmeida1994** [comment]
In my opinion we can merge it

**Comment by lmmendes** [comment]
I just reviewed your two commits on my side it's ok to merge!

**Comment by lmmendes** [comment]
@Jalmeida1994 after your merge I'm going to rebase #19 so that we can merge it also.

**Pull request merged**
