### PR TITLE
Chore: Add Docker Support

### PR DESCRIPTION
**Pull request by lmmendes**
Created Dockerfile using [chainguard/wolfi-base](https://images.chainguard.dev/directory/image/wolfi-base/overview) as base image. This image is security focused and out of the box runs on non-root user and has fewer dependencies reducing the attack surface.

Improved also the docker-compose.yml by adding [pgadmin](https://www.pgadmin.org) a PostgreSQL web UI to help the database visualisation during development.

### CODE REVIEW

**Comment by Jalmeida1994** [comment]
Any specific reason you're adding the binary from the local machine to the docker image? Don't you prefer running a multi-stage build, compiling the app and adding that to the later stage? We would need to install stuffbin in the docker container but perhaps that would make it more "contained".

I can do it. I'll pull this branch and make the necessary changes if you agree.

**Comment by lmmendes** [comment]
@Jalmeida1994 remember that the build of the artifact is handle by the gorelease plugin.

Or I'm seeing this wrong?

**Comment by Jalmeida1994** [comment]
Ahh of course! Completely forgot about it! I need to check up on goreleaser more!

**Review by Jalmeida1994 — APPROVED** [review]

**Comment by Jalmeida1994** [comment]
You can squash and merge if you want!

**Pull request merged**
