### PR TITLE
Initial implementation of migration

### PR DESCRIPTION
**Pull request by lmmendes**
this needs to be rebased with main

### CODE REVIEW

**Comment by lmmendes** [comment]
@Jalmeida1994 I hope that tomorrow we have migration working, most of to code is done it's just gluing the logic together.

**Review by Jalmeida1994 — COMMENTED** [review]
Screenshot 2024-11-05 at 08 39 25

Did not know that CI checks could appear on the referenced lines in the PR review view 👀

**Review by Jalmeida1994 — APPROVED** [review]

**Comment by Jalmeida1994** [comment]
Just missing some linter issues, but for example the install not being used is not important as it's a WIP feature.

**Comment by Jalmeida1994** [comment]
c

**Comment by lmmendes** [comment]
@Jalmeida1994 migrations are now working, at least the install of the new schema.

I'm now testing the usage of https://mathesar.org as a client interface for PostgreSQL to be included in the docker compose to aid with debug when not using IntelliJ

**Pull request merged**
